name: Build + Attest Both

on:
  workflow_dispatch:

jobs:
  build_and_attest:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn package

      # 3) Generate SBOM
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: './'
          format: 'spdx-json'
          output-file: 'sbom.json'

      # 4) Attest build provenance
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'output/app.txt'

      # 5) Attest SBOM
      - name: Attest SBOM
        uses: actions/attest-sbom@v3
        with:
          subject-path: 'target/my-java-app-1.0-SNAPSHOT.jar'
          sbom-path: 'sbom.json'
